nvim: Make headless installation of all plugins work
The ability to synchronously install all plugins and then exit vim
headlessly was lost quite some time ago. Write some lua code to get it
back and make our install script invoke it. Note, it is still sometimes
racy because there is no way to completely sure that treesitter is
finished compiling all parsers, but it mostly works for now.

Also add --no-nvim-plugins option to install so that you can choose to
install nvim without its plugins. Make it possibly to use --no-nvim but
not --no-nvim-plugins to ONLY install the plugins but not Nvim itself.
Useful if the OS already has a recent version of Nvim installed.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -123,6 +123,7 @@ opt_apt=1
 opt_locale=1
 opt_nodejs=1
 opt_nvim=1
+opt_nvim_plugins=1
 opt_tmux=1
 # Transform long options to short ones because getopts builtin is dumb and we don't
 # want to rely on external getopt.
@@ -137,13 +138,14 @@ for arg in "$@"; do
         "--no-locale") set -- "$@" "-l" ;;
         "--no-nodejs") set -- "$@" "-n" ;;
         "--no-nvim")   set -- "$@" "-m" ;;
+        "--no-nvim-plugins")   set -- "$@" "-M" ;;
         "--no-tmux")   set -- "$@" "-t" ;;
-        "--minimal")   set -- "$@" "-a" "-a" "-l" "-n" "-m" "-t" ;;
+        "--minimal")   set -- "$@" "-a" "-a" "-l" "-n" "-m" "-M" "-t" ;;
         "--help")      set -- "$@" "-h" ;;
         *)             set -- "$@" $arg ;;
     esac
 done
-while getopts "fyedalnmth" opt; do
+while getopts "fyedalnmMth" opt; do
     case ${opt} in
         f)
             opt_force=1
@@ -172,6 +174,9 @@ while getopts "fyedalnmth" opt; do
         m)
             opt_nvim=0
             ;;
+        M)
+            opt_nvim_plugins=0
+            ;;
         t)
             opt_tmux=0
             ;;
@@ -185,8 +190,9 @@ while getopts "fyedalnmth" opt; do
             echo "    --no-locale     Do not set up locales"
             echo "    --no-nodejs     Do not run install Node.js"
             echo "    --no-nvim       Do not run install Nvim"
+            echo "    --no-nvim-plugins Do not run install Nvim plugins"
             echo "    --no-tmux       Do not run install tmux plugins"
-            echo "    --minimal       Equiv. to  --no-apt --no-locale --no-nodejs --no-nvim --no-tmux"
+            echo "    --minimal       Equiv. to  --no-apt --no-locale --no-nodejs --no-nvim --no-nvim-plugins --no-tmux"
             echo "    -h, --help      Print this message"
             exit 1
     esac
@@ -345,12 +351,18 @@ if [[ $opt_nodejs == 1 ]] && (is_yes || promptyn 'Do you want to install node.js
     inst_nodejs
 fi
 
-if [[ $opt_nvim == 1 ]] && (is_yes || promptyn 'Do you want to install & configure Neovim AppImage?' Y); then
+if [[ $opt_nvim == 1 ]] && (is_yes || promptyn 'Do you want to install Neovim AppImage?' Y); then
     inst_nvim
     inst_virtualenv
     inst_neovim_remote
-    echo
-    if is_yes || promptyn 'Will now launch Neovim to install plugins. Manually exit it when finished. Proceed?' Y; then
-        nvim
+fi
+
+if [[ $opt_nvim_plugins == 1 ]] && (is_yes || promptyn 'Will now launch Neovim in headless mode to install plugins. Proceed?' Y); then
+    if ! which nvr; then    # Might have just done this in the $opt_nvim case
+        inst_neovim_remote
     fi
+    nvim --headless -c InstallAllPluginsSync -c qa
+    # nvim typically exits with status 1 even though it succeeded.
+    # Prevent whole script from exiting with failure status:
+    true
 fi
